### ISSUE TITLE
Allocating memory on stack might lead to corrupting stack

### ISSUE THREAD

**Issue by georgik** [mbv/ssd1680#1]
There is one problem which becomes visible when turning on esp-wifi, together with this crate.
esp-wifi will get corrupted stack, because we run out of the memory. Framebuffer is allocated on the stack.
For ESP32 and boards with PSRAM one solution could be to use allocator and pull the memory from PSRAM.
For ESP32-C3 probably the only solution is to shink the buffer.

**Comment by mbv** [comment]
@georgik I am good with your changes, Could you create PR?

**Comment by georgik** [comment]
Sure. I'm investigating the problem little bit more and it might have different root cause.
It seems that displays allocates only 4000 bytes per buffer, while it should be ~4039.
Basically this funnction returns incorrect data: 
```
const fn buffer_len(width: usize, height: usize) -> usize {
    (width + 7) / 8 * height
}
```
So it happens that `ssd1680.display_frame(&mut spi, &mut delay).unwrap();` basically does something beyond the buffer.

**Comment by georgik** [comment]
Again this might not be correct theory, but I believe that it has to do something with the end of buffer.

**Comment by mbv** [comment]
yep, that version sounds more logical to me too. I don't think the 4kb we use for buffer can affect the wifi stack. I'll review the driver documentation and how it is used here again

**Comment by mbv** [comment]
>So it happens that ssd1680.display_frame(&mut spi, &mut delay).unwrap(); basically does something beyond the scope of buffer.

This method just write the buffer to spi.

We should double check the setting of the buffer values: `let (index, bit) = find_position(point.x as u32, point.y as u32, width, height, rotation);`
https://github.com/mbv/ssd1680/blob/main/src/graphics.rs#L80C9-L80C99

**Comment by georgik** [comment]
Thank you for the suggestion. 

Meanwhile we tracked down problem which seems to be related to memory allocation on the stack when working with esp-wifi.
The working version is here: https://github.com/georgik/esp32-rust-lilygo-t5-epaper/tree/feature/working-wifi
To get non-working version it was sufficient to move rx, and tx buffers (1.5k) into the loop.
The issues with buffer for display is probably not away, it's just hidden under different buffer. 
So for ESP32 users we have kind of workaround.

**Comment by georgik** [comment]
The root cause of the problem was identified. It was caused by call of incorrect function in esp-hal. Instead of [ESP32Reset, there was function Reset](https://github.com/esp-rs/esp-hal/pull/823), which has differnet behavior. The problem manifested only in certain curner cases.
Solution is to upgrade to esp-hal 0.16.0.
The example now works without problem: https://github.com/georgik/esp32-rust-lilygo-t5-epaper

I'm closing the issue.
